[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
quadratic_fund = "4dJUHV6StKArznZ7Dd8dTDv6jmquhMbZu6YYzYJZcWW3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
